### ISSUE TITLE
Support for vs2015 (14.0) ?

### ISSUE THREAD

**Issue by MitchellHansen** [mrdooz/TabGroupJumper#3]
I built the project, added the Addins folder, put the files in there, and restarted vs to no avail. Did 2015 break this extension?

**Comment by mrdooz** [comment]
Hey,
I haven't had the chance to upgrade to VS2015 yet, but it sounds like something might have changed. I'll take a look as soon as I get the time.

**Comment by MitchellHansen** [comment]
Right on! Thank you!

**Comment by Cleroth** [comment]
2015 no longer has add-ins. You need to migrate to a VSPackage.
See [this](https://msdn.microsoft.com/en-us/library/dn246938(v=vs.140).aspx) and [this](http://www.visualstudioextensibility.com/2014/07/01/strategies-migrating-from-visual-studio-add-ins-to-packages/).

**Comment by dustin-biser** [comment]
I am also looking forward to this working for VS2015.  I cannot believe it's not a default feature.

**Comment by mrdooz** [comment]
I just updated this to use VSIX, so it works under VS2015. I now know why I'd been putting it off for so long, because it really wasn't fun at all :)

I made a new repository for the VSIX version, https://github.com/mrdooz/TabGroupJumperVSIX. It contains a prebuilt .vsix file in the bin directory, so you should just be able to run that, and be good to go.

**Comment by Cleroth** [comment]
Yea it didn't seem like a fun thing to do. Your hard work is appreciated, thanks. It's working for me.

**Comment by mrdooz** [comment]
Ok, that's great to hear! Closing this issue then.
